"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AuthGuard } from "@/components/auth-guard";
import { Modal } from "@/components/modal";
import { Shell } from "@/components/shell";
import { Button, Input, StatusBadge } from "@/components/ui";
import { classesApi, kodlandApi, type ClassRecord, type KodlandGroup, type KodlandStudent } from "@/lib/api";

const dateLabel = (value: string) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Não informada";
const statusTone = (value: string) => /ativo|active|regular/i.test(value) ? "success" as const : /pause|expul|inativ|churn/i.test(value) ? "danger" as const : "warning" as const;

function Center() {
  const [groups, setGroups] = useState<KodlandGroup[]>([]), [students, setStudents] = useState<KodlandStudent[]>([]), [classes, setClasses] = useState<ClassRecord[]>([]);
  const [username, setUsername] = useState(""), [password, setPassword] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [syncOpen, setSyncOpen] = useState(false);
  const [group, setGroup] = useState<KodlandGroup | null>(null), [student, setStudent] = useState<KodlandStudent | null>(null), [query, setQuery] = useState(""), [studentQuery, setStudentQuery] = useState("");
  const load = useCallback(async () => { const [a,b,c] = await Promise.all([kodlandApi.groups(), kodlandApi.students(), classesApi.list()]); setGroups(a.items); setStudents(b.items); setClasses(c.items); }, []);
  useEffect(() => { queueMicrotask(() => { void load().catch((error: Error) => setMessage(error.message)); }); }, [load]);
  const visibleGroups = useMemo(() => groups.filter((item) => `${item.title} ${item.course_name}`.toLowerCase().includes(query.toLowerCase())), [groups, query]);
  const visibleStudents = useMemo(() => students.filter((item) => (!group || item.external_class_id === group.external_id) && `${item.name} ${item.email} ${item.external_class_name}`.toLowerCase().includes(studentQuery.toLowerCase())).sort((a,b) => a.name.localeCompare(b.name)), [students, group, studentQuery]);
  async function sync(event: FormEvent) { event.preventDefault(); if (!username || !password) return setMessage("Informe usuário e senha da Kodland."); setBusy(true); try { const result = await kodlandApi.sync(username, password); setPassword(""); setSyncOpen(false); setMessage(`${result.group_count} turmas, ${result.student_count} alunos e ${result.review_count} correções atualizados.`); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível sincronizar."); } finally { setBusy(false); } }
  async function link(value: string) { if (!group) return; await kodlandApi.linkGroup(group.external_id, value || null); await load(); setGroup({...group, local_class_id: value || null}); }
  async function saveStudent(event: FormEvent) { event.preventDefault(); if (!student?.name.trim()) return; setBusy(true); try { await kodlandApi.updateStudent(student.id, { name: student.name.trim(), email: student.email.trim(), phone: student.phone.trim(), status: student.status.trim(), profile_url: student.profile_url.trim(), local_note: student.local_note.trim() }); await load(); setStudent(null); } finally { setBusy(false); } }
  async function hideStudent() { if (!student || !window.confirm(`Ocultar ${student.name} da lista local?`)) return; await kodlandApi.hideStudent(student.id); await load(); setStudent(null); }
  return <div className="management-grid">
    {message && <p className={message.includes("atualizados") ? "notice" : "form-error"}>{message}</p>}
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Central Kodland</p><h2>Gestão pedagógica simplificada</h2><p className="muted">Turmas, alunos, progresso e correções em uma única visão.</p></div><div className="card-actions"><Button type="button" onClick={() => setSyncOpen(true)}>Sincronizar dados</Button><a className="button button-ghost" href="/corrections">Ver correções</a></div></div></section>
    <section className="metric-grid"><article className="metric-card"><span>Turmas ativas</span><strong>{groups.filter((item) => !item.archived).length}</strong></article><article className="metric-card"><span>Alunos</span><strong>{students.length}</strong></article><article className="metric-card"><span>Correções</span><strong>→</strong><a href="/corrections">Abrir fila</a></article></section>
    <section className="panel"><div className="section-heading"><div><h2>Turmas</h2><p className="muted">Curso, agenda, alunos e vínculo financeiro.</p></div><Input aria-label="Buscar turma" placeholder="Buscar turma ou curso" value={query} onChange={(e) => setQuery(e.target.value)} /></div><div className="entity-list">{visibleGroups.map((item) => <button className="entity-card kodland-group-card" type="button" key={item.id} onClick={() => {setGroup(item); setStudentQuery("");}}><div><div className="entity-title"><h3>{item.title}</h3><StatusBadge tone={item.archived ? "neutral" : "success"}>{item.archived ? "Arquivada" : "Ativa"}</StatusBadge></div><p className="entity-details">{item.course_name || "Curso não informado"}</p><p className="muted">{students.filter((value) => value.external_class_id === item.external_id).length || item.student_count} aluno(s) · Próxima aula: {dateLabel(item.next_lesson_date)}</p></div><span className="button button-ghost">Abrir</span></button>)}</div>{!visibleGroups.length && <p className="muted">Nenhuma turma encontrada.</p>}</section>
    <section className="panel"><div className="section-heading"><div><h2>{group ? `Alunos — ${group.title}` : "Alunos"}</h2><p className="muted">Clique para consultar contato, progresso e observações locais.</p></div>{group && <button className="button button-ghost" type="button" onClick={() => setGroup(null)}>Todas as turmas</button>}</div><Input aria-label="Buscar aluno" placeholder="Buscar aluno, e-mail ou turma" value={studentQuery} onChange={(e) => setStudentQuery(e.target.value)} /><div className="entity-list kodland-students">{visibleStudents.map((item) => <button className="entity-card kodland-student-card" type="button" key={item.id} onClick={() => setStudent(item)}><div><div className="entity-title"><h3>{item.name}</h3>{item.status && <StatusBadge tone={statusTone(item.status)}>{item.status}</StatusBadge>}</div><p className="entity-details">{item.external_class_name} · Progresso: {item.progress_summary || "não informado"}</p><p className="muted">{item.email || item.phone || "Contato não informado"}</p></div><span className="button button-ghost">Detalhes</span></button>)}</div>{!visibleStudents.length && <p className="muted">Nenhum aluno encontrado.</p>}</section>
    <Modal open={syncOpen} title="Sincronizar com a Kodland" onClose={() => !busy && setSyncOpen(false)}><p className="muted">O acesso é usado somente nesta sincronização e não é salvo pelo AulaPay.</p><form className="form management-form" onSubmit={sync}><label className="field">Usuário Kodland<Input value={username} autoComplete="username" onChange={(e) => setUsername(e.target.value)} /></label><label className="field">Senha Kodland<Input type="password" value={password} autoComplete="current-password" onChange={(e) => setPassword(e.target.value)} /></label><div className="form-actions"><Button disabled={busy}>{busy ? "Sincronizando…" : "Sincronizar agora"}</Button></div></form></Modal>
    <Modal open={Boolean(group)} title={group?.title ?? "Turma"} onClose={() => setGroup(null)}>{group && <div className="form"><p className="entity-details">{group.course_name || "Curso não informado"}</p><p className="muted">Início: {dateLabel(group.start_date)}<br />Próxima aula: {dateLabel(group.next_lesson_date)}</p><label className="field">Vínculo com turma financeira<select className="input" value={group.local_class_id ?? ""} onChange={(e) => void link(e.target.value)}><option value="">Sem vínculo</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><p className="muted">Crie uma turma financeira na área Turmas antes de vinculá-la.</p></div>}</Modal>
    <Modal open={Boolean(student)} title={student?.name ?? "Aluno"} onClose={() => setStudent(null)}>{student && <form className="form management-form" onSubmit={saveStudent}><p className="muted field-wide">Turma: {student.external_class_name}<br />Progresso: {student.progress_summary || "não informado"}</p><label className="field">Nome<Input value={student.name} onChange={(e) => setStudent({...student, name: e.target.value})} /></label><label className="field">Status<Input value={student.status} onChange={(e) => setStudent({...student, status: e.target.value})} /></label><label className="field">E-mail<Input type="email" value={student.email} onChange={(e) => setStudent({...student, email: e.target.value})} /></label><label className="field">Telefone<Input value={student.phone} onChange={(e) => setStudent({...student, phone: e.target.value})} /></label><label className="field field-wide">Observação local<Input value={student.local_note} onChange={(e) => setStudent({...student, local_note: e.target.value})} /></label><div className="form-actions"><Button disabled={busy}>Salvar dados locais</Button>{student.phone && <a className="button button-ghost" target="_blank" rel="noreferrer" href={`https://wa.me/${student.phone.replace(/\D/g, "")}`}>WhatsApp</a>}{student.profile_url && <a className="button button-ghost" target="_blank" rel="noreferrer" href={student.profile_url}>Perfil Kodland</a>}<button className="button button-danger" type="button" onClick={() => void hideStudent()}>Ocultar</button></div></form>}</Modal>
  </div>;
}
export default function KodlandPage() { return <AuthGuard>{(user) => <Shell user={user}><Center /></Shell>}</AuthGuard>; }
