"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AuthGuard } from "@/components/auth-guard";
import { Shell } from "@/components/shell";
import { Button, Input, StatusBadge } from "@/components/ui";
import { classesApi, kodlandApi, type ClassRecord, type KodlandGroup, type KodlandStudent } from "@/lib/api";

function Content() {
  const [groups, setGroups] = useState<KodlandGroup[]>([]); const [students, setStudents] = useState<KodlandStudent[]>([]); const [classes, setClasses] = useState<ClassRecord[]>([]); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const [groupData, studentData, classData] = await Promise.all([kodlandApi.groups(), kodlandApi.students(), classesApi.list()]); setGroups(groupData.items); setStudents(studentData.items); setClasses(classData.items); }, []);
  useEffect(() => { queueMicrotask(() => { void load().catch((error: Error) => setMessage(error.message)); }); }, [load]);
  async function sync(event: FormEvent) { event.preventDefault(); if (!username || !password) return setMessage("Informe usuário e senha da Kodland."); setBusy(true); setMessage(""); try { const result = await kodlandApi.sync(username, password); setPassword(""); setMessage(`${result.group_count} turmas, ${result.student_count} alunos e ${result.review_count} correções atualizados.`); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível sincronizar."); } finally { setBusy(false); } }
  return <div className="management-grid"><section className="page-heading"><div><p className="eyebrow">Integração segura</p><h1>Kodland</h1><p className="muted">Turmas, alunos e entregas em um só painel.</p></div></section>{message && <p className={message.includes("atualizados") ? "notice" : "form-error"}>{message}</p>}<section className="panel"><h2>Sincronizar plataforma</h2><p className="muted">Suas credenciais são usadas somente agora e não são armazenadas pelo AulaPay.</p><form className="form management-form" onSubmit={sync}><label className="field">Usuário Kodland<Input value={username} autoComplete="username" onChange={(event) => setUsername(event.target.value)} /></label><label className="field">Senha Kodland<Input type="password" value={password} autoComplete="current-password" onChange={(event) => setPassword(event.target.value)} /></label><div className="form-actions"><Button disabled={busy}>{busy ? "Sincronizando…" : "Sincronizar agora"}</Button></div></form></section><section className="panel"><div className="section-heading"><h2>Turmas sincronizadas</h2><span className="muted">{groups.length}</span></div><div className="entity-list">{groups.map((group) => <article className="entity-card" key={group.id}><div><div className="entity-title"><h3>{group.title}</h3><StatusBadge tone={group.archived ? "neutral" : "success"}>{group.archived ? "Arquivada" : "Ativa"}</StatusBadge></div><p className="entity-details">{group.course_name || "Curso não informado"} · {students.filter((student) => student.external_class_id === group.external_id).length} aluno(s)</p></div><label className="field">Vincular à turma financeira<select className="input" value={group.local_class_id ?? ""} onChange={(event) => void kodlandApi.linkGroup(group.external_id, event.target.value || null).then(load)}><option value="">Sem vínculo</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></article>)}</div>{!groups.length && <p className="muted">Nenhuma turma sincronizada.</p>}</section><section className="panel"><div className="section-heading"><h2>Alunos</h2><span className="muted">{students.length}</span></div><div className="entity-list">{students.map((student) => <article className="entity-card" key={student.id}><div><div className="entity-title"><h3>{student.name}</h3>{student.status && <StatusBadge>{student.status}</StatusBadge>}</div><p className="entity-details">{student.external_class_name} · {student.progress_summary || "Progresso não informado"}</p><p className="muted">{student.email || student.phone || "Sem contato informado"}</p></div><div className="card-actions">{student.phone && <a className="button button-ghost" target="_blank" rel="noreferrer" href={`https://wa.me/${student.phone.replace(/\D/g, "")}`}>WhatsApp</a>}{student.profile_url && <a className="button button-ghost" target="_blank" rel="noreferrer" href={student.profile_url}>Perfil</a>}</div></article>)}</div></section></div>;
}

export default function KodlandPage() { return <AuthGuard>{(user) => <Shell user={user}><Content /></Shell>}</AuthGuard>; }
