export const labels = {
  appName: 'AulaPay',
  lastPaymentLabel: 'Último',
  nextPaymentLabel: 'Próximo',
  summaryTodayLabel: 'Até hoje',
  futureLabel: 'Futuro',
  classesLabel: 'Turmas',
  detailsLabel: 'Detalhes',
  paymentsLabel: 'Pagamentos',
  lessonsLabel: 'Aulas',
  earnedLabel: 'Ganhos',
  receivedLabel: 'Recebido',
  normalLabel: 'Normais',
  extraLabel: 'Extras',
  plannedLabel: 'Previsto',
  futureLessonsLabel: 'Aulas futuras',
  totalPlannedLabel: 'Total previsto',
  totalLessonsLabel: 'Total aulas',
  lessonsCountLabel: 'Aulas',
  percentLabel: '%',
};
