export type User = { id: string; name: string; email: string };
export type DashboardLesson = { id: string; class_id: string | null; class_name_snapshot: string; number: number; lesson_date: string; student: string; type: string; duration_minutes: number; hourly_rate_cents: number; period: string; payment_date: string; value_cents: number; status: string; };
export type DashboardPayment = { payment_date: string; period: string; lesson_count: number; normal_count: number; extra_count: number; normal_total_cents: number; extra_total_cents: number; total_cents: number; status: string; lessons: DashboardLesson[]; };
export type DashboardProgress = { class_id: string; name: string; lesson_count: number; completed: number; remaining: number; percent: number; };
export type DashboardResponse = { today: string; earned_cents: number; received_cents: number; normal_lessons: number; extra_lessons: number; normal_earned_cents: number; extra_earned_cents: number; planned_cents: number; future_lessons: number; total_planned_cents: number; total_lessons: number; last_payment: DashboardPayment | null; next_payment: DashboardPayment | null; payments: DashboardPayment[]; progress: DashboardProgress[]; };
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
export class ApiError extends Error { constructor(public readonly status: number, message: string) { super(message); } }
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { const response = await fetch(`${apiUrl}${path}`, { ...init, credentials: "include", headers: { "Content-Type": "application/json", ...init.headers } }); if (!response.ok) { const body: unknown = await response.json().catch(() => null); const message = typeof body === "object" && body !== null && "detail" in body && typeof body.detail === "string" ? body.detail : "Não foi possível concluir a operação."; throw new ApiError(response.status, message); } return response.status === 204 ? undefined as T : response.json() as Promise<T>; }
export const authApi = { me: () => request<User>("/api/v1/users/me"), login: (email:string,password:string) => request<User>("/api/v1/auth/login",{method:"POST",body:JSON.stringify({email,password})}), register: (name:string,email:string,password:string) => request<User>("/api/v1/auth/register",{method:"POST",body:JSON.stringify({name,email,password})}), logout: () => request<void>("/api/v1/auth/logout",{method:"POST"}) };
export const dashboardApi = { get: (asOf?: string) => request<DashboardResponse>(`/api/v1/dashboard${asOf ? `?as_of=${encodeURIComponent(asOf)}` : ""}`) };
