export type User = { id: string; name: string; email: string };
export type DashboardLesson = { id: string; class_id: string | null; class_name_snapshot: string; number: number; lesson_date: string; student: string; type: string; duration_minutes: number; hourly_rate_cents: number; period: string; payment_date: string; value_cents: number; status: string };
export type DashboardPayment = { payment_date: string; period: string; lesson_count: number; normal_count: number; extra_count: number; normal_total_cents: number; extra_total_cents: number; total_cents: number; status: string; lessons: DashboardLesson[] };
export type DashboardProgress = { class_id: string; name: string; lesson_count: number; completed: number; remaining: number; percent: number };
export type DashboardResponse = { today: string; earned_cents: number; received_cents: number; normal_lessons: number; extra_lessons: number; normal_earned_cents: number; extra_earned_cents: number; planned_cents: number; future_lessons: number; total_planned_cents: number; total_lessons: number; last_payment: DashboardPayment | null; next_payment: DashboardPayment | null; payments: DashboardPayment[]; progress: DashboardProgress[] };
export type ClassRecord = { id: string; name: string; week_day: number; start_time: string; first_lesson_date: string; lesson_count: number; duration_minutes: number; hourly_rate_cents: number; active: boolean };
export type ClassPayload = Omit<ClassRecord, "id" | "active">;
export type Lesson = DashboardLesson & { active: boolean; canceled: boolean; note: string };
export type LessonList = { items: Lesson[]; total: number; page: number; page_size: number };
export type ExtraLessonPayload = { student: string; lesson_date: string; duration_minutes: number; hourly_rate_cents: number; note: string };
export type LessonFilters = { type?: "NORMAL" | "EXTRA"; status?: "ACTIVE" | "CANCELED" | "COMPLETED" | "FUTURE"; from?: string; to?: string; page?: number; page_size?: number };
export type PaymentDetail = DashboardPayment & { received_at: string | null; confirmation_note: string | null };
export type ImportReport = { export_id: string; already_imported: boolean; class_count: number; lesson_count: number; payment_confirmation_count: number; total_cents: number; imported_at: string | null };
export type DataExport = { schema_version: "1.0"; exported_at: string; user: User; classes: unknown[]; lessons: unknown[]; payment_confirmations: unknown[] };
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
export class ApiError extends Error { constructor(public readonly status: number, message: string) { super(message); } }
async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`${apiUrl}${path}`, { ...init, credentials: "include", headers: { "Content-Type": "application/json", ...init.headers } });
  if (!response.ok) { const body: unknown = await response.json().catch(() => null); const detail = typeof body === "object" && body !== null && "detail" in body ? body.detail : null; const message = typeof detail === "string" ? detail : Array.isArray(detail) ? "Revise os campos informados." : "Não foi possível concluir a operação."; throw new ApiError(response.status, message); }
  return response.status === 204 ? undefined as T : response.json() as Promise<T>;
}
export const authApi = { me: () => request<User>("/api/v1/users/me"), login: (email:string,password:string) => request<User>("/api/v1/auth/login",{method:"POST",body:JSON.stringify({email,password})}), register: (name:string,email:string,password:string) => request<User>("/api/v1/auth/register",{method:"POST",body:JSON.stringify({name,email,password})}), logout: () => request<void>("/api/v1/auth/logout",{method:"POST"}) };
export const dashboardApi = { get: (asOf?: string) => request<DashboardResponse>(`/api/v1/dashboard${asOf ? `?as_of=${encodeURIComponent(asOf)}` : ""}`) };
export const classesApi = { list: (active = true) => request<{ items: ClassRecord[]; total: number }>(`/api/v1/classes?active=${active}`), create: (payload: ClassPayload) => request<ClassRecord>("/api/v1/classes", { method: "POST", body: JSON.stringify(payload) }), update: (id: string, payload: Partial<ClassPayload>) => request<ClassRecord>(`/api/v1/classes/${id}`, { method: "PATCH", body: JSON.stringify(payload) }), deactivate: (id: string) => request<ClassRecord>(`/api/v1/classes/${id}/deactivate`, { method: "POST" }) };
export const lessonsApi = { list: (filters: LessonFilters = {}) => { const query = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value !== undefined && value !== "") query.set(key, String(value)); }); return request<LessonList>(`/api/v1/lessons${query.size ? `?${query}` : ""}`); }, createExtra: (payload: ExtraLessonPayload) => request<Lesson>("/api/v1/lessons/extras", { method: "POST", body: JSON.stringify(payload) }), cancel: (id: string) => request<Lesson>(`/api/v1/lessons/${id}/cancel`, { method: "POST" }) };
export const paymentsApi = { list: () => request<{ items: DashboardPayment[]; total: number }>("/api/v1/payments"), get: (paymentDate: string) => request<PaymentDetail>(`/api/v1/payments/${paymentDate}`), confirm: (paymentDate: string, note = "") => request<{ payment: DashboardPayment; received_at: string; note: string }>(`/api/v1/payments/${paymentDate}/confirm`, { method: "POST", body: JSON.stringify({ note }) }), reverse: (paymentDate: string) => request<void>(`/api/v1/payments/${paymentDate}/confirmation`, { method: "DELETE" }) };
export const dataApi = { export: () => request<DataExport>("/api/v1/data/export"), previewImport: (payload: unknown) => request<ImportReport>("/api/v1/data/import/preview", { method: "POST", body: JSON.stringify(payload) }), import: (payload: unknown) => request<ImportReport>("/api/v1/data/import", { method: "POST", body: JSON.stringify(payload) }), reset: (password: string) => request<void>("/api/v1/data", { method: "DELETE", body: JSON.stringify({ confirmation: "RESETAR", password }) }) };
